# Default values for chainsaw-account.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: app/chainsaw-user-service
  tag: 0.0.1-SNAPSHOT
  pullPolicy: Never

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chainsaw-user-service
      paths: []
  tls: []

livenessProbe:
  httpGet:
    path: /user
    port: 8080

readinessProbe: 
  httpGet:
    path: /user
    port: 8080

env:
  - name: ENVIRONMENT
    value: "development"
  - name: QUARKUS_DATASOURCE_URL
    value: "jdbc:postgresql://acid-minimal-cluster:5432/dbtest"
  - name: QUARKUS_SSL_ENABLED
    value: "false" 

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
