# Default values for chainsaw-config-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: app/chainsaw-config-server
  tag: 0.0.1-SNAPSHOT
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chainsaw-config-server
      paths: []
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
