spring:
  application:
    name: chainsaw-config-server
  management:
    enable: true
  profiles:
    active: default
  cloud:
    config:
      server:
        git:
          uri: https://github.com/brunojensen/configuration
          clone-on-start: true
          skipSslValidation: true
